name: GCP Federated Auth

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  auth-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: "projects/651379271034/locations/global/workloadIdentityPools/digify-pool/providers/digify-github-provider"
          service_account: "digify-app-accessor@digify-458811.iam.gserviceaccount.com"

      - name: Verify authentication
        run: |
          gcloud info
          gcloud auth list
