name: Build test with Direct WIF

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - '**'

permissions:
  id-token: write
  contents: read

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          token_format: access_token
          workload_identity_provider: "projects/651379271034/locations/global/workloadIdentityPools/digify-pool/providers/digify-github-provider"
          service_account: digify-public@digify-458811.iam.gserviceaccount.com
          create_credentials_file: true
          export_environment_variables: true
          cleanup_credentials: true
          access_token_lifetime: 3600s
          access_token_scopes: https://www.googleapis.com/auth/cloud-platform
          retries: 3
          backoff: 250
          id_token_include_email: false
    
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Fetch Secrets from Secret Manager
        run: |
          BILLINGO_API_KEY=$(gcloud secrets versions access latest --secret="billingo-api-key")
          BUCKET_NAME=$(gcloud secrets versions access latest --secret="bucket-name")
          CLOUDINARY_API_KEY=$(gcloud secrets versions access latest --secret="cloudinary-api-key")
          CLOUDINARY_API_SECRET=$(gcloud secrets versions access latest --secret="cloudinary-api-secret")
          CLOUDINARY_CLOUD_NAME=$(gcloud secrets versions access latest --secret="cloudinary-cloud-name")
          DATABASE_PASSWORD=$(gcloud secrets versions access latest --secret="database-password")
          DATABASE_USERNAME=$(gcloud secrets versions access latest --secret="database-username")
          DATASOURCE_URL=$(gcloud secrets versions access latest --secret="datasource-url")
          GOOGLE_MAPS_GEOCODING_API_KEY=$(gcloud secrets versions access latest --secret="google-maps-geocoding-api-key")
          JWT_SECRET_KEY=$(gcloud secrets versions access latest --secret="jwt-secret-key")
          MAIL_HOST=$(gcloud secrets versions access latest --secret="mail-host")
          MAIL_PASSWORD=$(gcloud secrets versions access latest --secret="mail-password")
          MAIL_PORT=$(gcloud secrets versions access latest --secret="mail-port")
          MAIL_SMTP_SSL_TRUST=$(gcloud secrets versions access latest --secret="mail-smtp-ssl-trust")
          MAIL_USERNAME=$(gcloud secrets versions access latest --secret="mail-username")
          OPENAI_API_KEY=$(gcloud secrets versions access latest --secret="openai-api-key")

          # Mask secrets
          echo "::add-mask::$BILLINGO_API_KEY"
          echo "::add-mask::$BUCKET_NAME"
          echo "::add-mask::$CLOUDINARY_API_KEY"
          echo "::add-mask::$CLOUDINARY_API_SECRET"
          echo "::add-mask::$CLOUDINARY_CLOUD_NAME"
          echo "::add-mask::$DATABASE_PASSWORD"
          echo "::add-mask::$DATABASE_USERNAME"
          echo "::add-mask::$DATASOURCE_URL"
          echo "::add-mask::$GOOGLE_MAPS_GEOCODING_API_KEY"
          echo "::add-mask::$JWT_SECRET_KEY"
          echo "::add-mask::$MAIL_PASSWORD"
          echo "::add-mask::$MAIL_USERNAME"
          echo "::add-mask::$OPENAI_API_KEY"

          # Export env vars
          echo "BILLINGO_API_KEY=$BILLINGO_API_KEY" >> $GITHUB_ENV
          echo "BUCKET_NAME=$BUCKET_NAME" >> $GITHUB_ENV
          echo "CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY" >> $GITHUB_ENV
          echo "CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET" >> $GITHUB_ENV
          echo "CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUD_NAME" >> $GITHUB_ENV
          echo "DATABASE_PASSWORD=$DATABASE_PASSWORD" >> $GITHUB_ENV
          echo "DATABASE_USERNAME=$DATABASE_USERNAME" >> $GITHUB_ENV
          echo "DATASOURCE_URL=$DATASOURCE_URL" >> $GITHUB_ENV
          echo "GOOGLE_MAPS_GEOCODING_API_KEY=$GOOGLE_MAPS_GEOCODING_API_KEY" >> $GITHUB_ENV
          echo "JWT_SECRET_KEY=$JWT_SECRET_KEY" >> $GITHUB_ENV
          echo "MAIL_HOST=$MAIL_HOST" >> $GITHUB_ENV
          echo "MAIL_PASSWORD=$MAIL_PASSWORD" >> $GITHUB_ENV
          echo "MAIL_PORT=$MAIL_PORT" >> $GITHUB_ENV
          echo "MAIL_SMTP_SSL_TRUST=$MAIL_SMTP_SSL_TRUST" >> $GITHUB_ENV
          echo "MAIL_USERNAME=$MAIL_USERNAME" >> $GITHUB_ENV
          echo "OPENAI_API_KEY=$OPENAI_API_KEY" >> $GITHUB_ENV

      - name: Build project
        run: ./gradlew build
